export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <div className="antialiased flex justify-center items-center h-screen w-screen">
        {children}
      </div>
    </>
  );
}
